# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SortingAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoName', models.CharField(max_length=50)),
                ('algoComplexity', models.CharField(max_length=50)),
                ('algoDetails', models.CharField(max_length=2000)),
            ],
        ),
    ]
